#!/bin/bash
# my_init.d step (runs before runit starts nginx): expose wireguard-ui under BASE_PATH on the
# Seafile nginx (:80), so the container's single HTTP port serves both:  / -> Seafile,
# $BASE_PATH -> UI. The reverse proxy on the host sends the whole domain here.
# Seafile's server block includes this file (the include is added to the image's
# seafile.nginx.conf.template in the Dockerfile). Regenerated on every start, so changing
# WGUI_BASE_PATH in .env needs no edit of the persisted seafile.nginx.conf.
set -eu

out=/etc/nginx/wireguard-ui.locations
base="${BASE_PATH:-}"
# Same normalisation as the UI (util.ParseBasePath): leading slash, no trailing slash.
[ -z "$base" ] || base="/${base#/}"
base="${base%/}"

if [ -z "$base" ]; then
  echo "# BASE_PATH is empty: wireguard-ui is not exposed on this nginx (it would clash with Seafile at /)." > "$out"
  echo "nginx-ui-locations: BASE_PATH empty, UI not added to nginx"
  exit 0
fi

cat > "$out" <<NGINX
# Generated by /etc/my_init.d/02_nginx_ui_locations.sh from BASE_PATH=$base. Do not edit.
location ~ ^${base}(/|\$) {
    proxy_pass http://127.0.0.1:5000;
    proxy_http_version 1.1;
    proxy_set_header Host \$http_host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    # Keep the outer proxy's scheme (https from Traefik); empty = header dropped on direct access.
    proxy_set_header X-Forwarded-Proto \$http_x_forwarded_proto;
    proxy_set_header Connection "";
    proxy_read_timeout 300s;
    client_max_body_size 16m;
    access_log /var/log/nginx/wireguard-ui.access.log seafileformat;
    error_log  /var/log/nginx/wireguard-ui.error.log;
}
NGINX
echo "nginx-ui-locations: wireguard-ui served at ${base} on the Seafile nginx"
